### ISSUE TITLE
Popup menu with `manual_complete` does not update items

### ISSUE THREAD

**Issue by phgz** [Shougo/ddc-ui-native#1]
**Ubuntu 20.04.5 or MacOS 13.0.1
NVIM v0.9.0-dev-550+g3ea1524cf**

See `minimal.txt` file for reproduction with packages and settings.

When opening popup menu with `manual_complete`, the menu does not update items in the list when typing characters. This only happens with `manual_complete`. If main UI is `native`, then list is updated when typing characters.

To reproduce (here, main UI is `none`):

1. convert minimal.txt to minimal.lua
2. nvim -u minimal.lua
4. do `<S-Tab>` in insert mode to open manual completion
5. Start typing one of the suggestion.

Problem is present with `completeopt = "menu,menuone,noselect"` or default `completeopt` when going to previous item on first suggestion.

[minimal.txt](https://github.com/Shougo/ddc-ui-native/files/10326815/minimal.txt)

**Comment by Shougo** [comment]
Please don't use plugin manager in it.

**Comment by Shougo** [comment]
Reproduced.  But it is expected behavior.  The update items features are auto complete feature.
It is already disabled by your config.

**Comment by phgz** [comment]
I am not sure I understand (where is it disabled?), but if it is the expected behaviour, then I will live with it.

Thanks anyway to have checked! Next time I won't use plugin manager.

**Comment by Shougo** [comment]
> Next time I won't use plugin manager.

Thanks.

> I am not sure I understand (where is it disabled?), but if it is the expected behaviour, then I will live with it.

You have disabled sources in default and you have use `none` UI.  It means disable auto completion.

But I have changed ddc.vim auto completion behavior.
Please update ddc.vim to the latest.

**Comment by phgz** [comment]
It is working now, Awesome! Thanks for the fast feature :)
